### ISSUE TITLE
Character encoding 

### ISSUE THREAD

**Issue by WouterDePrins** [FlyingDiver/Indigo-MQTT#11]
For example - "I'm On Fire" becomes` "I&#x27;m On Fire"`

**Comment by WouterDePrins** [comment]
I didn't use a template, I just published the device :)

**Comment by FlyingDiver** [comment]
That’s not possible. I guess you used the default template.

**Comment by WouterDePrins** [comment]
Ah ok, yes, then I used the default one :)

**Comment by FlyingDiver** [comment]
Can you do a device dump for that device and post it here?  There’s a short python script for doing so that has been posted to the forums.  I can’t find it for you, I’m working on a very slow connection from Viet Nam.

**Comment by FlyingDiver** [comment]
I really do need to see what the actual device states are of the Airfoil device.  Otherwise I'm going to have to close this incident.

**Comment by WouterDePrins** [comment]
Any idea where I could find the python script? I can't find it on the forums...

**Comment by FlyingDiver** [comment]
I'm back home with access to my dev system now....

    indigo.server.log(unicode(indigo.devices[21692342]))

Edit the device number.

**Comment by WouterDePrins** [comment]
Got it - thanks! 

```
batteryLevel : None
buttonGroupCount : 0
configured : True
description : Main device for the 'iMac van Wouter' Airfoil instance
deviceTypeId : airfoil
displayStateId : status
displayStateImageSel : SensorOn
displayStateValRaw : connected
displayStateValUi : connected
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 1909254552
globalProps : MetaProps : (dict)
     com.perceptiveautomation.indigoplugin.airfoilpro : (dict)
          address : MacBook-Pro-van-Wouter.local:53557 (string)
          afInstance : MacBook Pro van Wouter (string)
          iTunesDeviceId :  (string)
          pathToImages : /Users/wouterdeprins/Desktop/AlbumArt/ (string)
          savedSource : (list)
               Item : /Applications/iTunes.app (string)
               Item : recentApplications (string)
          savedSpeakerStates : (list)
               Item : (list)
                    Item : 1185812357 (integer)
                    Item : false (bool)
               Item : (list)
                    Item : 363092022 (integer)
                    Item : true (bool)
               Item : (list)
                    Item : 1032203439 (integer)
                    Item : false (bool)
               Item : (list)
                    Item : 1294554172 (integer)
                    Item : false (bool)
               Item : (list)
                    Item : 833302880 (integer)
                    Item : false (bool)
               Item : (list)
                    Item : 1426610709 (integer)
                    Item : false (bool)
          version : 1 (integer)
id : 330928664
lastChanged : 2020-03-19 18:54:54
lastSuccessfulComm : 2020-03-19 18:54:54
model : Airfoil Instance
name : iMac van Wouter
ownerProps : com.perceptiveautomation.indigoplugin.airfoilpro : (dict)
     address : MacBook-Pro-van-Wouter.local:53557 (string)
     afInstance : MacBook Pro van Wouter (string)
     iTunesDeviceId :  (string)
     pathToImages : /Users/wouterdeprins/Desktop/AlbumArt/ (string)
     savedSource : (list)
          Item : /Applications/iTunes.app (string)
          Item : recentApplications (string)
     savedSpeakerStates : (list)
          Item : (list)
               Item : 1185812357 (integer)
               Item : false (bool)
          Item : (list)
               Item : 363092022 (integer)
               Item : true (bool)
          Item : (list)
               Item : 1032203439 (integer)
               Item : false (bool)
          Item : (list)
               Item : 1294554172 (integer)
               Item : false (bool)
          Item : (list)
               Item : 833302880 (integer)
               Item : false (bool)
          Item : (list)
               Item : 1426610709 (integer)
               Item : false (bool)
     version : 1 (integer)
pluginId : com.perceptiveautomation.indigoplugin.airfoilpro
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     canConnect : true (bool)
     canRemoteControl : true (bool)
     instanceName : MacBook Pro van Wouter (string)
     protocolVersion : 1.5 (string)
     sourceAlbum : 7 Layers (string)
     sourceArtist : Dotan (string)
     sourceGroup : recentApplications (string)
     sourceIdentifier : /Applications/Spotify.app (string)
     sourceMachineModel : MacBookPro11,1 (string)
     sourceMachineName : MacBook Pro van Wouter (string)
     sourceMetadataAvailable : MacBook Pro van Wouter (string)
     sourceName : Spotify (string)
     sourcePlayStatus : unavailable (string)
     sourcePlayStatus.error : false (bool)
     sourcePlayStatus.paused : false (bool)
     sourcePlayStatus.playing : false (bool)
     sourcePlayStatus.stopped : false (bool)
     sourcePlayStatus.unavailable : true (bool)
     sourceRemoteControlAvailable : true (bool)
     sourceTrackName : Home II (string)
     status : connected (string)
     status.connected : true (bool)
     status.disconnected : false (bool)
     status.unavailable : false (bool)
subModel : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : False
```

**Comment by FlyingDiver** [comment]
Please do it again, this time while the problematic track is playing.

**Comment by WouterDePrins** [comment]
"It's Too Late EP" is shown as  `IT&#X27;S TOO LATE`

```
states : States : (dict)
     canConnect : true (bool)
     canRemoteControl : true (bool)
     instanceName : MacBook Pro van Wouter (string)
     protocolVersion : 1.5 (string)
     sourceAlbum : It's Too Late EP (string)
     sourceArtist : Wild Belle (string)
     sourceGroup : recentApplications (string)
     sourceIdentifier : /Applications/Spotify.app (string)
     sourceMachineModel : MacBookPro11,1 (string)
     sourceMachineName : MacBook Pro van Wouter (string)
     sourceMetadataAvailable : MacBook Pro van Wouter (string)
     sourceName : Spotify (string)
     sourcePlayStatus : unavailable (string)
     sourcePlayStatus.error : false (bool)
     sourcePlayStatus.paused : false (bool)
     sourcePlayStatus.playing : false (bool)
     sourcePlayStatus.stopped : false (bool)
     sourcePlayStatus.unavailable : true (bool)
     sourceRemoteControlAvailable : true (bool)
     sourceTrackName : It's Too Late (string)
     status : connected (string)
     status.connected : true (bool)
     status.disconnected : false (bool)
     status.unavailable : false (bool)

```

**Comment by FlyingDiver** [comment]
Is it actually capitalized like that?  Because it's not all caps in the device state.

**Comment by FlyingDiver** [comment]
I'm going to need to see the actual MQTT payload as well.  What MQTT client are you using?

**Comment by WouterDePrins** [comment]
No, I have capitalised it on the web page but it's also visible like that (see below) in the MQTT Broker (Mosquitto).

` {'name': 'iMac van Wouter', 'deviceId':'330928664','model': 'Airfoil Instance', 'address': 'MacBook-Pro-van-Wouter.local:53557', 'states': { 'canConnect': 'True', 'canRemoteControl': 'True', 'instanceName': 'MacBook Pro van Wouter', 'protocolVersion': '1.5', 'sourceAlbum': 'It&#x27;s Too Late EP', 'sourceArtist': 'Wild Belle', 'sourceGroup': 'recentApplications', 'sourceIdentifier': '/Applications/Spotify.app', 'sourceMachineModel': 'MacBookPro11,1', 'sourceMachineName': 'MacBook Pro van Wouter', 'sourceMetadataAvailable': 'MacBook Pro van Wouter', 'sourceName': 'Spotify', 'sourcePlayStatus': 'unavailable', 'sourcePlayStatus.error': 'False', 'sourcePlayStatus.paused': 'False', 'sourcePlayStatus.playing': 'False', 'sourcePlayStatus.stopped': 'False', 'sourcePlayStatus.unavailable': 'True', 'sourceRemoteControlAvailable': 'True', 'sourceTrackName': 'It&#x27;s Too Late', 'status': 'connected', 'status.connected': 'True', 'status.disconnected': 'False', 'status.unavailable': 'False' } }`

**Comment by FlyingDiver** [comment]
OK, I can recreate this on my system now.  I need to research how to correct this.  The problem is that the apostrophe is a reserved character for the JSON strings.  I think I need to double-quote the string before I output it.

**Comment by WouterDePrins** [comment]
Aaah yes, that's probably the issue. I had also some issues with the variable template but I got that fixed by adjusting the variable template. (can't recall the exact problem but it was also something with quotes or brackets)

**Comment by FlyingDiver** [comment]
This is not correctable.  Or to be more accurate, it's working correctly now.  Certain characters MUST be encoded inside the JSON payload.  

So the question is - how are you accessing the JSON payload?  When you convert the JSON back to Python (for example), those strings should be automatically un-escaped.

**Comment by WouterDePrins** [comment]
Hi Joe, 

I'm parsing the MQTT data to JSON in Javascript. 
I also noticed there are some differences in single and double quotes when pushing different kind of devices:

This one is a Zwave device:
`{"name": "Living: Muur Tafel - Licht", "deviceId":"462686059","model": "Flush Micro Dimmer (ZMNHDD)", "address": "34", "states": { "accumEnergyTimeDelta": "0", "accumEnergyTimeDelta.ui": "0 seconds", "accumEnergyTotal": "12.5", "accumEnergyTotal.ui": "12.5 kWh", "brightnessLevel": "0", "curEnergyLevel": "0.0", "curEnergyLevel.ui": "0.0 W", "onOffState": "False" } }`

This one is a virtual device:
` {'name': 'Living: Scene Chill Lichten', 'deviceId':'1882998032','model': 'Device Group', 'address': '', 'states': { 'onOffState': 'False' } }`

**Comment by FlyingDiver** [comment]
Are you using JSON.parse() or writing your own parser?

**Comment by WouterDePrins** [comment]
I just use JSON.parse(). For the virtual devices I have to convert the single quotes to double quotes, otherwise I get the `Unexpected token ' in JSON at position 1` error message.

**Comment by FlyingDiver** [comment]
Edit the device publishing template and change all the single quotes to double quotes.

**Comment by WouterDePrins** [comment]
I already did that but that didn't change anything.

**Comment by FlyingDiver** [comment]
> I already did that but that didn't change anything.

I find that hard to believe. Make sure they're all double-quotes, then restart the plugin.  Delete all devices from the published list and re-add them.

**Comment by WouterDePrins** [comment]
Ok, that's fixed, I had to remove the topics in the broker. Now all devices and variables have double quotes. This doesn't fix the `'` and  `&` problem.

**Comment by FlyingDiver** [comment]
It wouldn't, but using JSON.parse() should.  So you shouldn't be looking at the MQTT message contents, but what you get at the other end in Javascript.

**Comment by WouterDePrins** [comment]
When I convert the MQTT message to a string (.toString()), I get the same: 

`{"name": "iMac van Wouter", "deviceId":"330928664","model": "Airfoil Instance", "address": "MacBook-Pro-van-Wouter.local:53557", "states": { "canConnect": "True", "canRemoteControl": "True", "instanceName": "MacBook Pro van Wouter", "protocolVersion": "1.5", "sourceAlbum": "Home Again (Deluxe Version)", "sourceArtist": "Michael Kiwanuka", "sourceGroup": "recentApplications", "sourceIdentifier": "/Applications/Spotify.app", "sourceMachineModel": "MacBookPro11,1", "sourceMachineName": "MacBook Pro van Wouter", "sourceMetadataAvailable": "MacBook Pro van Wouter", "sourceName": "Spotify", "sourcePlayStatus": "unavailable", "sourcePlayStatus.error": "False", "sourcePlayStatus.paused": "False", "sourcePlayStatus.playing": "False", "sourcePlayStatus.stopped": "False", "sourcePlayStatus.unavailable": "True", "sourceRemoteControlAvailable": "True", "sourceTrackName": "I&#x27;ll Get Along", "status": "connected", "status.connected": "True", "status.disconnected": "False", "status.unavailable": "False" } `

Converting in to JSON doesn't do the trick.

**Comment by FlyingDiver** [comment]
You need to convert FROM JSON, not to JSON.  You should not be using toString().  See https://stackoverflow.com/questions/4935632/parse-json-in-javascript

**Comment by WouterDePrins** [comment]
Hi Joe, sorry for my wrong explanation but I'm converting **from** JSON. You're right, I can leave out the toString() function but this doesn't fix the issue. It's a cosmetic issue, so I can fix it with a replace function. So I don't take too much from your time :)

**Comment by FlyingDiver** [comment]
Strange.  My reading implied that using JSON.parse() would reverse those escape sequences.  But I really don't know much Javascript at all.  Just enough to do some minimal work in node-red.

In any case, I don't think there's anything else I can do in the plugin to fix this.  I will change the default template to use double-quotes.
