### ISSUE TITLE
Message sent to mosquito with retain flag to 1 in message, but retain parameter is False 

### ISSUE THREAD

**Issue by turgu1** [FlyingDiver/Indigo-MQTT#12]
Hello,

Here is the mosquitto log entry related to the message sent by Indigo:

```
Received PUBLISH from indigo-mqtt-1578442998 (d0, q0, r1, m0, 'home/5CCF7F0727A1/blinds', ... (11 bytes))
```

I tried both values for the Retain parameter in the Indigo message configuration, but this does not change the retain flag in the message sent. How can I get messages sent without having the messages retained by the MQTT broker?

Thanks!!

**Comment by FlyingDiver** [comment]
How exactly are you sending the message?  Python script?  Indigo action?  Please post code or screenshot, respectively.

**Comment by turgu1** [comment]
An Indigo action

**Comment by turgu1** [comment]
![Screen Shot 2020-04-18 at 21 01 18](https://user-images.githubusercontent.com/174329/79992134-1e2af200-8481-11ea-93df-0a62f8c25951.jpeg)

**Comment by turgu1** [comment]
I tried both values for the Retain parameter, but the end result is always de same: the retain flag in the message received by mosquitto is always 1.

**Comment by FlyingDiver** [comment]
Huh.  OK, I'll look into it.

**Comment by turgu1** [comment]
Thanks!

**Comment by turgu1** [comment]
Here are the config panels

**Comment by turgu1** [comment]
![Screen Shot 2020-04-22 at 10 24 38](https://user-images.githubusercontent.com/174329/79994182-9eeaed80-8483-11ea-8f79-63bd30b377f7.jpeg)

**Comment by FlyingDiver** [comment]
I found the bug.  Fixed version out soon.

**Comment by turgu1** [comment]
Excellent!!! Thanks for this very fast service effort!!
