### ISSUE TITLE
Updated device states don't publish when multiple MQTT Broker devices are defined in Indigo

### ISSUE THREAD

**Issue by lukebrannon1** [FlyingDiver/Indigo-MQTT#13]
Today I created a second MQTT Broker device in Indigo as I had a different category of devices I needed to publish to MQTT that require a different device publishing template.

What I've found is that only one of the MQTT Broker devices will publish. They will both receive topics they are subscribed to, but only one of them (seems like only the one that was started first) will publish. I can make the non-working one work by disabling Indigo communication for the working one then reloading the plugin. 

I am running Mosquitto on another machine (RPi) on my local network. I have been able to replicate this behavior on two separate Mosquitto servers (one localhost, the other not).

When looking at the debug logs it appears to dump out a list of Indigo Device IDs that are published. That list of IDs corresponds to the devices that are actually updating their status to MQTT and, again, they are all part of only one of the Indigo MQTT Broker devices.

Any thoughts? Please let me know what log or configuration data might be helpful. I am running version 0.4.5.

Thanks!

**Comment by FlyingDiver** [comment]
I'll look into it.

**Comment by FlyingDiver** [comment]
Fixed in release 0.4.6, I think.

**Comment by lukebrannon1** [comment]
Initial testing looks good! Thank you. Right now I only have 2 MQTT Broker devices in Indigo but plan to add more as I continue building out MQTT for my setup. Is there a practical limit to the number of Broker devices or do you expect the fix made in 0.4.6 should allow several Broker devices (within reason, of course)?

**Comment by FlyingDiver** [comment]
No limit in the code.  They're fairly lightweight, so it shouldn't be a problem to have a dozen or so anyway.
