### ISSUE TITLE
make queue.qsize a configurable parameter

### ISSUE THREAD

**Issue by Ramias1** [FlyingDiver/Indigo-MQTT#15]
Please make queue.qsize on line 941 of plugin.py configurable -- currently hard coded to 10.  This will prevent unneeded warning messages when more than 10 items per message type queue up for a momentary instance.

see https://forums.indigodomo.com/viewtopic.php?f=316&t=24679&start=15#p198074

thanks

**Comment by FlyingDiver** [comment]
Implemented in 0.4.8.
