### ISSUE TITLE
Unable to connect to MQTTS server due to expired CA root certs

### ISSUE THREAD

**Issue by turribeach** [FlyingDiver/Indigo-MQTT#18]
The desired MQTT server I want to connect via MQTTS uses certificates issued by [LetsEncrypt](https://letsencrypt.org/). Recently some of the root CA certs LetsEcrypt uses have expired and need to be updated. This caused lots of trouble for older devices (see [here](https://techcrunch.com/2021/09/21/lets-encrypt-root-expiry/)) like my MacOS Mojave MacMini. Technically Mojave is still under Apple Support but it seems they don't care much. I looked around on how to update the OS CA root certs but looks like this is not easy to do as the certs are protected by System Integrity Protection (see [here](http://tenfourfox.blogspot.com/2021/10/curl-lets-encrypt-and-apple-laziness.html)).

Please expose the ca_certs parameter of TLS_SET() as per https://pypi.org/project/paho-mqtt/#option-functions so that an updated ca_certs file with the new LetsEncrypt CA root certs can be used. 

Thanks!

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-MQTT/releases/tag/0.4.12

**Comment by turribeach** [comment]
Thanks Joe, that's working now. However one small issue is that the path of the ca_certs is relative, even when I use an absolute path:

`
   MQTT Connector Debug            Glowmarkt MQTT Broker: Specified cert file '/Library/Application Support/Perceptive Automation/Indigo 2021.2//usr/local/Cellar/ca-certificates/2021-10-26/share/ca-certificates/cacert.pem' doesn't exist, using default cert_file
`
For now I have used a relative path and placed the cert_file under the Indigo folder but I think it will be better if a absolute path could be used so that I can place the ca_certs file outside the Indigo installation directory. Otherwise every timne I upgrade Indigo Server I will need to remember to move the ca_certs file.

Also I see you fixed the error propagation issue with the library, which now correctly shows the issue with the SSL connection not being able to validate the certificate without an update ca_certs file:

`
   MQTT Connector Debug            Glowmarkt MQTT Broker: Broker __init__ address = glowmqtt.energyhive.com, port = 8883, protocol = 4, transport = tcp
   MQTT Connector Debug            Glowmarkt MQTT Broker: Enabling library level debugging
   MQTT Connector Debug            Glowmarkt MQTT Broker: No cert file provided, using default cert_file
   MQTT Connector Debug            Glowmarkt MQTT Broker: Broker connect error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
`

Thanks!

**Comment by FlyingDiver** [comment]
Yes, I added the exception error to the logging.  I went back and forth on the path.  I need to check with Matt and Jay on where's a good place to put files that need to be migrated with upgrades.  I think they're now doing that, but I need to document where to put them.  If that's not possible, I'll change it to make it optional.

**Comment by FlyingDiver** [comment]
Hmm.  I could check for a leading slash, and use absolute path if there is one.  That's probably best.

**Comment by turribeach** [comment]
Yeah that will do, as I can place it anywhere I want and then it wouldn't matter where Indigo is installed. I already have such directory where I keep my Indigo custom scripts.

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-MQTT/releases/tag/0.4.13

**Comment by turribeach** [comment]
Many thanks, that's all working now. Closing the issue.
