### ISSUE TITLE
Unable to Print Aggregator Data to Log

### ISSUE THREAD

**Issue by Ramias1** [FlyingDiver/Indigo-MQTT#19]
Troubleshooting a separate issue with an MQTT shim.  My aggregators are all there in the GUI.

Trying to print them to the log results in:

   MQTT Connector Error            Error in plugin execution MenuAction:

  File "plugin.py", line 973, in logAggregators
type: 'dict' object has no attribute 'iteritems'

version 2022.0.3

**Comment by FlyingDiver** [comment]
Oops.  Python3 conversion bug.

**Comment by FlyingDiver** [comment]
Fixed in 2022.0.4
