### ISSUE TITLE
MQTT Connector Error	Algemeen - MQTT Broker: Disconnected with result code 1

### ISSUE THREAD

**Issue by WouterKr** [FlyingDiver/Indigo-MQTT#2]
[mqttlog - disconnected with result code 1.txt](https://github.com/FlyingDiver/Indigo-MQTT/files/3538421/mqttlog.-.disconnected.with.result.code.1.txt)

Using :
- IndigoDomo 7.3
- MQTT Broker plugin v0.1.2 
- MQTT Shims plugin v0.1.0

After adding the subscription "wey3/devices/#" to the broker device it will give an error:

"MQTT Connector Error	Algemeen - MQTT Broker: Disconnected with result code 1"

Adding seperate subscriptions for mqtt connected devices does not give an message.

**Comment by FlyingDiver** [comment]
What are you using for an MQTT Broker, and can you get logs from it?

And turn the log level down to debugging, not detailed debugging.

**Comment by FlyingDiver** [comment]
Are you publishing devices individually or using exclude mode?

One problem I'm seeing is that the broker is sending back the same messages that you're publishing.  That leads to infinite loops.  There should be no reason to subscribe to the same topics you're sending.

**Comment by FlyingDiver** [comment]
Have you restarted the Broker since you upgraded to 0.1.2?  Please do so.  I think maybe it's caching topics that are causing a broadcast storm.

**Comment by WouterKr** [comment]
Using docker mosquitto on a macmini. Have it running now with less debugging.
I had the seperate subscriptions active. Maybe that is the reason? Deleted them and trying again.
Not much debugging from mosquitto though. Yes, restarted broker and shims (to be sure) has been restarted.

**Comment by FlyingDiver** [comment]
You can turn on debug mode on Mosquitto by editing the command line the docker container runs.

But not sure how you see the logs.  I run mine on my Synology, and it has a web page to show the log output.

**Comment by FlyingDiver** [comment]
It's this line I'm concerned about:
```
2019-08-25 18:55:22.294	MQTT Connector Threaddebug	Algemeen - MQTT Broker: Message received: wey3/devices/1923094310/last_topic, payload: {"deviceName": "Algemeen - MQTT Broker", "state": "last_topic", "newValue": "wey3/devices/470758418/Pi_2_Distance", "oldValue": "wey3/devices/piBeacon - C1/Pi_2_Distance"}
```
That shows the plugin receiving a topic message for the broker device itself.  That should not be happening.  And that newValue is some sort of bogus.  Like you have a bad template for the device published.

Shut down the broker totally.  Then make sure you're not publishing any messages about any MQTT devices (Connector or Shims).  Then disable the plugin, restart the broker, then enable the plugin.

**Comment by WouterKr** [comment]
Ok, must look into that. This it what is shows in the terminal screen:

1566755450: New connection from 172.17.0.1 on port 1883.
1566755450: New client connected from 172.17.0.1 as indigo-mqtt-1923094310 (c1, k60).
1566755570: Socket error on client indigo-mqtt-1923094310, disconnecting.

[LogSmall-MQTT.txt](https://github.com/FlyingDiver/Indigo-MQTT/files/3538443/LogSmall-MQTT.txt)

I am not seeing any strange things in here.

Will check the logging on mosquitto...........

=======================

You are fast ;-) Will disable and enable things again.

**Comment by WouterKr** [comment]
Seems I have to edit the config of moquitto. Will get back to you on that.
The line you mention above: I am running the GreenSkyMQTT plugin (which I hope to replace). I thought they could run side by side but can it be this is not the case?

**Comment by FlyingDiver** [comment]
Running them both is probably causing the problem.

As long as they're publishing and subscribing to different topics it should be OK, but if they're both using the same topics then you can get into a "feedback" loop.  Which causes the broadcast storm, which overloads the network buffers, which causes the disconnect.

**Comment by WouterKr** [comment]
Since I disabled the GreenSkyMQTT plugin your plugin is running without the disconnected message longer than is has done before with the subscription on "wey3/devices/#"

**Comment by WouterKr** [comment]
They are on different topics all but one for testing.......

**Comment by FlyingDiver** [comment]
I suggest turning that one off.  ;)

**Comment by WouterKr** [comment]
Haha, Since your plugin is more flexible I certainly will. But I had to test it first ;-)

Just enabled the GreenSky and immediatly I am having the message again.

Thanks for you quick help and another great plugin.

Is it already "mature" enough to replace the other one?

**Comment by FlyingDiver** [comment]
I think it's stable enough.  Mature enough depends on if it has the capabilities you need.

**Comment by WouterKr** [comment]
Great then I should make some changes. You are right and that is what I meant.
Have some wemos 4ch relays running. Thinking what the most generic way is to configure these.
The combination of trigger and shims is giving a lot of flexibility

**Comment by FlyingDiver** [comment]
That was the goal.

**Comment by WouterKr** [comment]
Well, hope to replace the other plugin soon.
Thanks again for your help.
