### ISSUE TITLE
MQTT - Topics with the same name

### ISSUE THREAD

**Issue by mwoodage** [FlyingDiver/Indigo-MQTT#20]
Hello,
I'm trying to get information from my battery inverter via MQTT, which i've managed to do quite successfully. However I can't get the information from the topic GivEnergy/SA2230***/Power/Power/Grid_Power because when configuring the topic component match, it will not let you have two names that are the same I.E. "power" "power".

Is there any way around this?

Thanks

**Comment by FlyingDiver** [comment]
Not sure why that restriction is in there.  I think it might be because I borrowed the code that does the list from a different plugin where dups were not allowed.

**Comment by FlyingDiver** [comment]
Fixed in 2022.0.5

**Comment by mwoodage** [comment]
Wow, super quick response, thank you - i'll give it a try now :)
