### ISSUE TITLE
Enhancement - OpenDXL Connector

### ISSUE THREAD

**Issue by MycroftVonLipwig** [FlyingDiver/Indigo-MQTT#3]
Please could you implement support for connection and authentication to OpenDXL if possible:

https://github.com/opendxl
https://github.com/opendxl/opendxl-client-python

**Comment by FlyingDiver** [comment]
Decided to look into this a little today.  I was able to get the broker running in Docker, and with some finagling I was able to run the sample scripts.

Note:  ``pip install cffi`` needed on MacOS X to use the python client.

**Comment by FlyingDiver** [comment]
Got a version for testing.  It's in it's own branch, so I'm not doing tags or releases yet.

https://github.com/FlyingDiver/Indigo-MQTT/tree/dxl

Use the green "Clone or download" button to get the latest.

You must have the Python library installed per your second link in the first post.  Plus see my note in an earlier post today.  You need to run the Provisioning steps, and configure the device with the cert and key files created.

**Comment by MycroftVonLipwig** [comment]
Excelent. Thanks! I cant seem to find your post about Provisioning. I am assuming this is why i get

 Reloading plugin "MQTT Connector 0.2.0"
   Starting plugin "MQTT Connector 0.2.0" (pid 1453)
   MQTT Connector Error            Error in plugin execution InitializeMain:

Traceback (most recent call last):
  File "plugin.py", line 17, in <module>
  File "/Library/Application Support/Perceptive Automation/Indigo 7.3/Plugins/MQTT Connector.indigoPlugin/Contents/Server Plugin/dxl_broker.py", line 9, in <module>
ImportError: No module named dxlclient.client

   Stopping plugin "MQTT Connector 0.2.0" (pid 1453)
   Stopped plugin "MQTT Connector 0.2.0"

**Comment by FlyingDiver** [comment]
It's referenced in this link:  https://github.com/opendxl/opendxl-client-python

Specifically, https://opendxl.github.io/opendxl-client-python/pydoc/installation.html

Test your SSL version as it shows, then do:

```
pip install dxlclient
pip install cffi
```

**Comment by MycroftVonLipwig** [comment]
Got it. OK so i have provisioned ok and showing connected on the MQTT Broker device in Indigo. Just trying to publish and/or receive a message. It seems subscribing to # is not a thing (or im doing something wrong which is highly likley). So far so good. Ill update shortly.

**Comment by MycroftVonLipwig** [comment]
OK So in ePO i published a test message on DXL and it was received by subscribing to QoS Level1 1:#. I will try publishing from Indigo but need to think of a way to receive it in ePO. Looks like it is working to me though. Will keep playing but looking good to me.

Thanks for this! This should add some over the top effects (Voice/Light colour changes etc) to any SOC including mine!

**Comment by FlyingDiver** [comment]
Oh yeah, QoS is ignored for DXL.  It doesn't have the concept, but I didn't want to change the subscribe/publish UI.

**Comment by MycroftVonLipwig** [comment]
OK so can get threats now in Indigo: 

{"eventMsgVersion":"1.0","eventMsgType":"McAfee Common Event","event":{"target":{"protocol":"","port":0,"fileName":"/Users/andrew/Downloads/eicar.com.txt.download/eicar.com.txt","userName":"Random-MacBook-Pro-5.local\\andrew","processName":"","hostName":"","ipv6":"192.168.x.x","ipv4":"192.168.x.x","mac":""},"analyzer":{"name":"McAfee Endpoint Security","id":"ENDP_AM_1060MACX","version":"10.6.4","engineVersion":"6010.8670","detectedUTC":"2019-09-26T16:17:13.000Z","contentVersion":"9391.0000","detectionMethod":"On-Access Scan","hostName":"Random-MacBook-Pro-5","ipv6":"192.168.x.x","ipv4":"192.168.x.x","mac":"BxEx5x3xCxFx"},"source":{"url":"","userName":"","processName":"Safari","hostName":"","ipv6":"192.168.x.x","ipv4":"192.168.x.x","mac":""},"threatHandled":1,"category":"Malware detected","entity":{"id":"2EBA7B44-70D8-11E9-1AF7-B8E8563FC4FC","type":"device","osPlatform":"Workstation","osType":"macOS","_nodeTextPath":"GlobalRoot\\Directory\\OS X"},"threatType":"Test-Virus(NOT A VIRUS)","threatSeverity":2,"threatActionTaken":"Deleted","eventDesc":"File infected.  No cleaner available, file deleted successfully","otherData":{"threatSeverityString":"Critical","responseRuleName":"Send Threat Event via DXL","definedAt":"My Organization","responseEventType":"Threat","count":"1"},"threatName":"EICAR test file","_receivedUTC":"2019-09-26T16:18:00.000Z","id":1278}}

Now to figure out what the best way to "do" something is when something matched something. Might need a bit of guidance on that but can ask you on Indigo Forum as I think connector wise this is doing exactly what I had hoped. Thanks again!

**Comment by FlyingDiver** [comment]
Released in 0.2.0.

**Comment by chrissmith-mcafee** [comment]
Hi-

Would it be possible for you to add this integration (solution) to [opendxl.com](https://opendxl.com)?

Thanks a lot!

Chris

**Comment by FlyingDiver** [comment]
@chrissmith-mcafee How do I do that?  Is there a place to submit them?
