### ISSUE TITLE
Request an automated reset for a cloud broker device when connection is lost

### ISSUE THREAD

**Issue by cuhouse** [FlyingDiver/Indigo-MQTT#4]
I have noticed that the CloudMQTT broker will error out to Disconnected 1 vice Connected 0. I verified that the CloudMQTT broker is still online as I can publish/control a device via MQTT Explorer. A reload of the MQTT Connector plugin always resolves the issue. To confirm that a break in the internet path is what is causing it, I disconnected the ethernet connection to the Mac Mini hosting Indigo and that caused the Disconnect 1 error. Is there some automation that could be put in place to reset the broker connection in the plugin for cases like this?

**Comment by FlyingDiver** [comment]
Fixed in 0.1.3
