### ISSUE TITLE
 MQTT Connector Error : Disconnected with result code 1

### ISSUE THREAD

**Issue by WouterKr** [FlyingDiver/Indigo-MQTT#5]
Hi,

After running both the connector en shims plugin and adding more devices I get this error again. It occures every 2 till 3 minutes. 
I configured two Broker devices with the Indigo ID's : 
303907606 : used for BT to MQTT gateway devices (publishing mac address beacons) / 1714999504 :used for regular devices like tasmota switch devices and other esp8266 based sensor devices

I am running:

Connector : v0.2.1 
Shims : V0.1.1
Mosquitto version 1.6.2 on a Synology NAS (Using Docker

I can not see what is going wrong looking at the mosquitto log. I addded the logfile of the mosquitto broker while this happens. Hopefully you can see what is causing the error. Please let me know I you need any additional informatie or if there is something I can do.
Thanks in advance.

Regards,

Wouter
[mosquitto.log](https://github.com/FlyingDiver/Indigo-MQTT/files/3720558/mosquitto.log)

**Comment by FlyingDiver** [comment]
First thing I would do is remove the "subscribe #" from both devices.

**Comment by FlyingDiver** [comment]
Nevermind last comment, was misreading log.

**Comment by WouterKr** [comment]
Thanks for the quick reply.
Ok, was already thinking about what to if I had to change the subscription.

**Comment by FlyingDiver** [comment]
What is actually generating the BT to MQTT messages?  They're coming in bursts every couple seconds.  Then eventually this happens:

    2019-10-12T10:40:41: Socket error on client indigo-mqtt-303907606, disconnecting.

**Comment by WouterKr** [comment]
These are coming from three esp8266 devices with a HM-10 bt-module. These devices are scanning for bluetooth devices and when it finds one it publishes its mac address. I am using beacons for this allowing me to see if a car is home or one of the family is home or leaving home

**Comment by FlyingDiver** [comment]
OK, let me think about this a bit.

**Comment by WouterKr** [comment]
That's fine. Hopefully you can think of something that can work with this. 
In addition to previous comment maybe this helps: I am use different shims devices which gets updated based on a trigger event with a matching mac address. When updated it in the reach of the scanning device so its home if not (for a period of time) it is away.

**Comment by FlyingDiver** [comment]
Are you auto-publishing any devices/variables with these brokers?  Or are they (mostly) receive only?  If it wouldn't be terribly hard, can you disable one of the devices and do both subscribes from the other?  So there's only one active MQTT Connector device?

**Comment by WouterKr** [comment]
The bt "beacons" connector is receiving only. The other is doing both but mostly receiving.
And if it help to find what is happening I surely can combine the two connector devices.
I had them combined with one connector device. But since the error occured the not BT devices suffered from a restart of the connector. Now only one is disconnecting and reconnecting.

**Comment by WouterKr** [comment]
You think it has something to doe with the amount of MQTT messages?

**Comment by FlyingDiver** [comment]
Maybe.  Probably not.

This error is reported a lot.  It might be a bug in mosquitto itself.  Or the Paho library the plugin is using.  Have you tried using a different broker?  Maybe even mosquitto in Docker on your Mac instead of your Synology?

**Comment by WouterKr** [comment]
;-) I had it on my MacMini in Docker. Because of our first contact I have moved things to my Synology NAS. I wanted to get some logging which was not possible on my Mac. Turns out it was an older version to.
Any suggestion for another broker?

**Comment by FlyingDiver** [comment]
You could use the public sandbox server at mqtt.eclipse.org, port 1883.  Just to see if you get the same error.

Run down your complete configuration for me.  You have some number of beacon devices (6? 10?) which are "discovered" by three esp8266 devices.  How often do these devices scan, and can a beacon be detected by more than one of them?

Those devices publish a topic like 'beacons/BTMQTT_Buiten/BTtoMQTT/536F095F041A', which identifies both the esp8266 device (BTMQTT_Buiten) and the beacon (536F095F041A).  

What happens when the MQTT Connector device receives that topic?  You have a trigger?  One trigger for all of them?  Or one per esp8266?  And the trigger(s) queue them for the MQTT Shims plugin?  Or do you run an action group based on the incoming topic?

What do you see in the Indigo log for the MQTT Connector plugin?  Just the error you reported above?  Nothing else?

**Comment by WouterKr** [comment]
Great idea; mqtt.eclipse.org is something I am going to try. See what happens.

Configuration:
Currently I am using 9 beacons. As you described these are discovered by three esp8266 devices with a bt module. All three are scanning with a interval of 500 ms during 20s and then start over again. During the scanning you are right : "Those devices publish a topic like 'beacons/BTMQTT_Buiten/BTtoMQTT/536F095F041A', which identifies both the esp8266 device (BTMQTT_Buiten/BTMQTT_Woonkamer/BTMQTT_Garage) and the beacon (536F095F041A)" with a rssi value {"rssi":73}

A trigger is used with a connector event matching a mac address. For every beacon there is a trigger. Using its own message type. This is message is queued for a MQTT Shims sensor device.
One Shims device for every beacon.
Based on topic component message type and unique id which is the mac address of the beacon.
Getting the payload key "rssi". If there is no update on the rssi value from all three esp8266 devices the beacon is not at home.
(Hope I described it in an way that you can make something out of it)

And yes, the only message in Indigo is the disconnected message.

**Comment by FlyingDiver** [comment]
If you put both the Connector plugin and Shims plugin in debug logging mode, is there any indication that's the a delay in getting the topic message to the shim?  You'll see entries like:
```
MQTT Connector Debug            cloud.flyingdiver.com Broker: queueMessageForDispatchAction, queue = ##SENSOR## (17)
```
Does that last number increment?  Or is it always 1 or 2?

**Comment by FlyingDiver** [comment]
I'm trying to figure out if the plugin's incoming socket connection is getting backed up due to the traffic.  If it's not, then it's got to be in the broker itself.  And I don't think there's anything I can do about that except maybe poll a little faster.

**Comment by FlyingDiver** [comment]
On other thing you could do is enable library logging in the plugin config dialog, then restart the plugin.  I'll need to see the section of the log right around the next disconnect.  Maybe there's an error at the library level that's causing this.

**Comment by WouterKr** [comment]
MQTT Connector Debug            MQTT - Connector for Beacons on DS916: queueMessageForDispatchAction, queue = ##beacon-wouter## **(1)**

Always (1)'s (So that is good; the one is the delay?)

```
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Buiten/BTtoMQTT/D93A0438E08F', ...  (12 bytes)
   MQTT Connector Debug            MQTT - Connector for Beacons on DS916: queueMessageForDispatchAction, queue = ##beacon-Auris## (1)
   MQTT Shims Debug                received notification of MQTT message type ##beacon-Auris## from MQTT - Connector for Beacons on DS916
   MQTT Connector Debug            MQTT - Connector for Beacons on DS916: fetchQueuedMessageAction, queue = ##beacon-Auris## (1)
   MQTT Shims Debug                Beacon - Auris: processMessages: '##beacon-Auris##' beacons/BTMQTT_Buiten/BTtoMQTT/D93A0438E08F -> {"rssi":-92}
   MQTT Shims Debug                Beacon - Auris: shimValueSensor, key = rssi, data = {u'rssi': -92}, value = -92
   MQTT Shims Debug                Beacon - Auris: Updating state to -92.0
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Garage/BTtoMQTT/00EA23410BF4', ...  (12 bytes)
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Woonkamer/BTtoMQTT/24DA11263301', ...  (12 bytes)
   MQTT Connector Debug            MQTT - Connector for Beacons on DS916: queueMessageForDispatchAction, queue = ##beacon-wouter## (1)
   MQTT Shims Debug                received notification of MQTT message type ##beacon-wouter## from MQTT - Connector for Beacons on DS916
   MQTT Connector Debug            MQTT - Connector for Beacons on DS916: fetchQueuedMessageAction, queue = ##beacon-wouter## (1)
   MQTT Shims Debug                Beacon - Wouter Sleutelbos: processMessages: '##beacon-wouter##' beacons/BTMQTT_Woonkamer/BTtoMQTT/24DA11263301 -> {"rssi":-58}
   MQTT Shims Debug                Beacon - Wouter Sleutelbos: shimValueSensor, key = rssi, data = {u'rssi': -58}, value = -58
   MQTT Shims Debug                Beacon - Wouter Sleutelbos: Updating state to -58.0
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Buiten/BTtoMQTT/24DA11262FB0', ...  (12 bytes)
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Garage/BTtoMQTT/DDD439416417', ...  (12 bytes)
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Woonkamer/BTtoMQTT/24DA11263301', ...  (12 bytes)
   MQTT Connector Debug            MQTT - Connector for Beacons on DS916: queueMessageForDispatchAction, queue = ##beacon-wouter## (1)
   MQTT Shims Debug                received notification of MQTT message type ##beacon-wouter## from MQTT - Connector for Beacons on DS916
   MQTT Connector Debug            MQTT - Connector for Beacons on DS916: fetchQueuedMessageAction, queue = ##beacon-wouter## (1)
   MQTT Shims Debug                Beacon - Wouter Sleutelbos: processMessages: '##beacon-wouter##' beacons/BTMQTT_Woonkamer/BTtoMQTT/24DA11263301 -> {"rssi":-58}
   MQTT Shims Debug                Beacon - Wouter Sleutelbos: shimValueSensor, key = rssi, data = {u'rssi': -58}, value = -58
   MQTT Shims Debug                Beacon - Wouter Sleutelbos: Updating state to -58.0
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Buiten/BTtoMQTT/24DA112630A5', ...  (12 bytes)
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Garage/BTtoMQTT/00EA23410BF7', ...  (12 bytes)
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Woonkamer/BTtoMQTT/24DA112630A5', ...  (12 bytes)
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Buiten/BTtoMQTT/7311F5A1E779', ...  (12 bytes)
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Garage/BTtoMQTT/D93A0438E08F', ...  (12 bytes)
   MQTT Connector Debug            MQTT - Connector for Beacons on DS916: queueMessageForDispatchAction, queue = ##beacon-Auris## (1)
   MQTT Shims Debug                received notification of MQTT message type ##beacon-Auris## from MQTT - Connector for Beacons on DS916
   MQTT Connector Debug            MQTT - Connector for Beacons on DS916: fetchQueuedMessageAction, queue = ##beacon-Auris## (1)
   MQTT Shims Debug                Beacon - Auris: processMessages: '##beacon-Auris##' beacons/BTMQTT_Garage/BTtoMQTT/D93A0438E08F -> {"rssi":-66}
   MQTT Shims Debug                Beacon - Auris: shimValueSensor, key = rssi, data = {u'rssi': -66}, value = -66
   MQTT Shims Debug                Beacon - Auris: Updating state to -66.0
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Woonkamer/BTtoMQTT/24DA112630A5', ...  (12 bytes)
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Buiten/BTtoMQTT/693884BAB9B5', ...  (12 bytes)
   MQTT Connector Debug            Sending PINGREQ
   MQTT Connector Debug            Received PUBLISH (d0, q0, r0, m0), 'beacons/BTMQTT_Garage/BTtoMQTT/24DA11268CA7', ...  (12 bytes)
   MQTT Connector Error            MQTT - Connector for Beacons on DS916: Disconnected with result code 1
   MQTT Connector Error            MQTT - Connector for Beacons on DS916: Disconnected with result code 1
```

**Sending PINGREQ ?**

**Comment by FlyingDiver** [comment]
It's the number of messages for that queue waiting on the shims plugin.  If you were using a shared queue then you might have several in there.  But since it's one beacon per queue, it means that the shim is updated before the next matching topic arrives.  Which is good.

**Comment by FlyingDiver** [comment]
I wonder if your DS916 has the cpu cycles to run this.  What CPU utilization does the Synology dashboard show?

**Comment by WouterKr** [comment]
Total CPU usage is 31% at the moment peaks to 50%.
The Docker image is running at 0.03% and uses 8Mb RAM
Should not be the problem I think
I had the same error when I had the broker on my mac mini (in Docker also)

**Comment by FlyingDiver** [comment]
OK, so it's not that.  Unless it's the docker version itself.  Using another broker might help.

Maybe the log file with library logging enabled will have a clue.

**Comment by WouterKr** [comment]
The comment with the debug lines includes library debugging selected. The only thing I can see what happens before the error is “SENDING PINGREQ”

**Comment by FlyingDiver** [comment]
Oh, you're right.  I had forgotten which messages came from where.

The “SENDING PINGREQ” is normal.  It's required by the spec to tell the broker you're still listening.  Happens every 15 seconds, I think.

I really think this is a broker issue.  It's just dropping the connection for no reason.  Well, it thinks it has a socket error, but I don't think the client (plugin) is causing it.  More likely an OS issue on the broker's side.

But hey, the reconnect is working properly.  So maybe this is just something to ignore.

**Comment by WouterKr** [comment]
Yes, the reconnect is working really good ;-)
And the plugins are great and really flexible. That’s why I got the idea of presence detection doing this way. But that may be to much......

Will try the public broker and see if it gives the same error.  Will let you know.

**Comment by FlyingDiver** [comment]
You could also try slowing it down some.  You said "500 ms during 20s".  What's that mean exactly for sending the updates?  Could you slow it down so it only sends a topic every 2 or 3 seconds?  If all three are sending at the same time, you could be getting three messages in a 500ms window.  I think.

**Comment by WouterKr** [comment]
The update frequency is merely for arriving car presence. To open gate and garagedoor because of the small range of the beacons sending power.
But yes, I was thinking the same thing for two of the three esp8266 devices.

**Comment by WouterKr** [comment]
Power off of one of the esp8266 devices did not help ;-)

**Comment by WouterKr** [comment]
mqtt.eclipse.org is giving me the same error. 
Playing now with the scan time and interval values on the esp8266 devices.

**Comment by WouterKr** [comment]
Hi, you can close this issue. I was not able to get it a steady respone with the amount off messages.
Thanks for your help.
