### ISSUE TITLE
OpenDXL Cert Folder location moved to inside the plugin

### ISSUE THREAD

**Issue by MycroftVonLipwig** [FlyingDiver/Indigo-MQTT#9]
In 0.3.2 it looks like the location for the certs needed for OpenDXL has moved from "/Users/indigo/Documents/opendxlcerts/" to "/Library/Application Support/Perceptive Automation/Indigo 7.4//Users/indigo/Documents/opendxlcerts/"

I have copied my certs into this structure (does not seem to care about that double forward slash) and all is well but looks like a bug?

Starting plugin "MQTT Connector 0.3.2" (pid 61257)
   MQTT Connector Debug            MQTT Connector: logLevel = 10, loopDelay = 0.1
   Started plugin "MQTT Connector 0.3.2"
   MQTT Connector                  Starting MQTT Connector
   MQTT Connector                  DXL Broker: Starting Device
   MQTT Connector Debug            DXL Broker: Broker __init__ address = 172.16.1.1, ca_bundle = /Library/Application Support/Perceptive Automation/Indigo 7.4//Users/indigo/Documents/opendxlcerts/ca-bundle.crt, cert_file = /Library/Application Support/Perceptive Automation/Indigo 7.4//Users/indigo/Documents/opendxlcerts/client.crt, private_key = /Library/Application Support/Perceptive Automation/Indigo 7.4//Users/indigo/Documents/opendxlcerts/client.key
   MQTT Connector Error            exception in deviceStartComm(DXL Broker): [Errno 2] No such file or directory
   MQTT Connector                  DXL Broker Events Only: Starting Device
   MQTT Connector Debug            DXL Broker Events Only: Broker __init__ address = 172.16.1.1, ca_bundle = /Library/Application Support/Perceptive Automation/Indigo 7.4//Users/indigo/Documents/opendxlcerts/ca-bundle.crt, cert_file = /Library/Application Support/Perceptive Automation/Indigo 7.4//Users/indigo/Documents/opendxlcerts/client.crt, private_key = /Library/Application Support/Perceptive Automation/Indigo 7.4//Users/indigo/Documents/opendxlcerts/client.key
   MQTT Connector Error            exception in deviceStartComm(DXL Broker Events Only): [Errno 2] No such file or directory
   MQTT Connector                  MQTT Broker: Starting Device

**Comment by FlyingDiver** [comment]
Actually, that was documented in the release notes:  https://github.com/FlyingDiver/Indigo-MQTT/releases/tag/0.3.0

The path in the config is now relative to the install directory, not absolute.
